#!/bin/sh

# $1 -- elf file
# $2 -- addr

CNT=`arm-linux-androideabi-addr2line -f -i -e $1 $2 | wc -l`
echo cnt: $CNT

if [ "$CNT" -eq "2" ]; then
FUN=`arm-linux-androideabi-addr2line -f -e $1 $2 | head -1`
else
FUN=`arm-linux-androideabi-addr2line -p -f -i -e $1 $2 | tail -1 | awk -F " at " '{print $1}' | awk -F " " '{print $3}'`
fi
echo fun: $FUN

echo a2l:
arm-linux-androideabi-addr2line -p -f -i -e $1 $2
echo '-------------------------------------------------------'
arm-linux-androideabi-addr2line -C -p -f -i -e $1 $2
echo '-------------------------------------------------------'

echo "dis: arm-linux-androideabi-objdump -d $1 | sed \"/<$FUN>:/,/^$/!d\""
arm-linux-androideabi-objdump -d $1 | sed "/<$FUN>:/,/^$/!d" | arm-linux-androideabi-c++filt

